version: '2'

services:

  packagist:
    restart: always
    image: dockette/packagist:app

    ports:
      # Production mode
      - 8000:8000
      - 80:8000
      #- 443:8000
      # Development mode
      - 9000:9000
      # Supervisor
      #- 9001:9001

      # You should create your own SSH keys
      # ===================================
      #volumes:
      #  - ./config/ssh/config:/var/www/.ssh/config
      #  - ./config/ssh/id_rsa:/var/www/.ssh/id_rsa
      #  - ./config/ssh/id_rsa.pub:/var/www/.ssh/id_rsa.pub
      #  - ./config/ssh/known_hosts:/var/www/.ssh/known_hosts

    environment:
      - PACKAGIST_DATABASE_USER=packagist
      - PACKAGIST_DATABASE_PASSWORD=packagist
    
    depends_on:
      - mysql
      - redis
      - solr

  mysql:
    restart: always
    image: mariadb:10.1

    volumes:
      - ./data/mysql:/var/lib/mysql
    
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=packagist
      - MYSQL_USER=packagist
      - MYSQL_PASSWORD=packagist

  redis:
    restart: always
    image: redis:3.2

    volumes:
      - ./data/redis:/data

  solr:
    image: dockette/packagist:solr

    volumes:
      - ./data/solr:/opt/solr/server/solr/mycores
