#!/bin/bash

PROJECT=packagist

case "$1" in
	build)
		docker-compose -p $PROJECT build
		exit 0
		;;

	remove)
		docker-compose -p $PROJECT stop
		docker-compose -p $PROJECT rm --all
		exit 0
		;;

	logs)
		docker-compose -p $PROJECT logs -f
		exit 0
		;;

	start)
		docker-compose -p $PROJECT up -d
		exit 0
		;;

	*)
		cat << EOF
Usage: ${0##*/} build | start | remove | logs
EOF
		exit 1
		;;
esac
shift