#!/bin/bash
su www-data -s /bin/sh -c 'php /srv/bin/console packagist:update --delete-before --no-debug -v --force --env=prod' >> /var/log/cron.log 2>&1
su www-data -s /bin/sh -c 'php /srv/bin/console packagist:dump --no-debug -v --force --env=prod' >> /var/log/cron.log 2>&1
su www-data -s /bin/sh -c 'php /srv/bin/console packagist:dump-v2 --no-debug -v --force --env=prod' >> /var/log/cron.log 2>&1
su www-data -s /bin/sh -c 'php /srv/bin/console packagist:index --no-debug -v --force --env=prod' >> /var/log/cron.log 2>&1
